tools:
  external_code_coverage:
    timeout: 600
  php_sim: true
  php_pdepend: true
  php_analyzer: true
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]
    excluded_paths: [Tests/*, test/*, src/Quickstart/AppBundle/Tests/*]
