fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

quickstart_app:
    resource: "@QuickstartAppBundle/Resources/config/routing.yml"
    prefix:   /

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
